CREATE TABLE IF NOT EXISTS address (
  id INT AUTO_INCREMENT PRIMARY KEY,
  address VARCHAR(255),
  postal_code VARCHAR(5),
  city VARCHAR(100),
  country VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS client (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100),
  name VARCHAR(100) NOT NULL,
  business_name VARCHAR(255),
  phone VARCHAR(15),
  address_id INT,
  FOREIGN KEY (address_id) REFERENCES address(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  UNIQUE (code),
  FOREIGN KEY (client_id) REFERENCES client(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;
